# Generated by Django 3.1.5 on 2021-01-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
